#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use SwiftPHP\Scaffold\Scaffold;

$loader = require __DIR__ . '/vendor/autoload.php';
$loader->addPsr4('SwiftPHP\\Scaffold\\', __DIR__ . '/Scaffold/');

Scaffold::getInstance()->run($_SERVER['argv']);